#use_frameworks!
#source 'https://github.com/CocoaPods/Specs.git'
#source 'git@hdfgit:/Data/git/ios/HDFSpecs.git'

platform :ios, '8.0'

target 'VIZHDFTestKit_Example' do
  pod 'VIZHDFTestKit', :path => '../'

  target 'VIZHDFTestKit_Tests' do
    inherit! :search_paths

    
  end
end
